# Generated by Django 4.2.7 on 2024-12-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_products_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='user',
        ),
    ]
